---
abstract: 'Parse and format PostgreSQL dates and times'
author:
  - 'Daisuke Maki <daisuke@endeworks.jp>'
build_requires:
  ExtUtils::MakeMaker: '6.36'
  Test::More: '0'
configure_requires:
  Module::Build::Tiny: '0.035'
dynamic_config: 0
generated_by: 'Minilla/v3.1.11, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DateTime-Format-Pg
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  DateTime::Format::Pg:
    file: lib/DateTime/Format/Pg.pm
    version: '0.16014'
requires:
  DateTime: '0.10'
  DateTime::Format::Builder: '0.72'
  DateTime::TimeZone: '0.05'
resources:
  bugtracker: https://github.com/lestrrat-p5/DateTime-Format-Pg/issues
  homepage: https://github.com/lestrrat-p5/DateTime-Format-Pg
  repository: git://github.com/lestrrat-p5/DateTime-Format-Pg.git
version: '0.16014'
x_contributors:
  - 'Daisuke Maki <lestrrat+github@gmail.com>'
  - 'David Steinbrunner <dsteinbrunner@pobox.com>'
  - 'Henrik Pauli <henrik.pauli@gmail.com>'
  - 'Ilya Chesnokov <chesnokov.ilya@gmail.com>'
  - 'Nitish Bezzala <nbezzala@yahoo.com>'
  - 'Steve Rogerson <steve.git@yewtc.demon.co.uk>'
  - 'Steve Rogerson <steve.rogerson@orionwt.co.uk>'
  - 'Vasily Chekalkin <bacek@bacek.com>'
  - 'lestrrat <49281+lestrrat@users.noreply.github.com>'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_static_install: 1
